---
host: 0.0.0.0
port: 9000
base_url: /
session_secret: mango-session-secret
library_path: /home/debian/mango/library
db_path: /home/debian/mango/mango.db
scan_interval_minutes: 5
thumbnail_generation_interval_hours: 24
log_level: info
upload_path: /home/debian/mango/uploads
plugin_path: /home/debian/mango/plugins
download_timeout_seconds: 30
library_cache_path: /home/debian/mango/library.yml.gz
cache_enabled: true
cache_size_mbs: 50
cache_log_enabled: true
disable_login: false
default_username: ""
auth_proxy_header_name: ""
mangadex:
  base_url: https://mangadex.org
  api_url: https://api.mangadex.org/v2
  download_wait_seconds: 5
  download_retries: 4
  download_queue_db_path: /home/debian/mango/queue.db
  chapter_rename_rule: '[Vol.{volume} ][Ch.{chapter} ]{title|id}'
  manga_rename_rule: '{title}'
